name: Curious_RL
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - scipy=1.6.2
  - opencv==4.6.0
  - pip=22.1.2
  - pip:
    - matplotlib==3.5.2
    - numpy==1.23.1
    - imageio==2.19.3
    - pygame==2.1.2
    - gym==0.26.2
    - mujoco==2.1.2
    - "--extra-index-url https://download.pytorch.org/whl/nightly/cpu"
    - torch; sys_platform != "linux" and sys_platform != "win32" and platform_machine == "arm64"
    - "--extra-index-url https://download.pytorch.org/whl/cpu"
    - torch==1.11.0; sys_platform != "linux" and sys_platform != "win32"
    - "--extra-index-url https://download.pytorch.org/whl/cpu"
    - torch==1.11.0; sys_platform == "linux" or sys_platform == "win32"